[package]
name = "git-ce"
version = "0.4.0"
edition = "2021"
license = "0BSD"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = { version = "0.19.0", default-features = false }
inquire = "0.7.5"

[dev-dependencies]
tempfile = "3.14.0"
