[package]
name = "git-ce"
version = "0.1.0"
edition = "2021"
license = "0BSD"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.7"
dialoguer = { version = "0.10.4", features = ["fuzzy-select"] }
git2 = "0.17.2"
