# Publish the Nix flake outputs to Cachix
name: Cachix
on:
  push:
    branches:
      - main

jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest]
    name: Publish Flake for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup Magic Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Authenticate with Cachix
      uses: cachix/cachix-action@v12
      with:
        name: git-ce
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Run Checks
      run: nix flake check -L --accept-flake-config

    - name: Build nix flake
      run: nix build -L --accept-flake-config
